[package]
name = "fw"
version = "1.7.3-pre"
authors = ["brocode <bros@brocode.sh>"]
description = "faster workspace management"
license = "WTFPL"
categories = ["command-line-utilities"]
repository = "https://github.com/brocode/fw"
readme = "README.org"
keywords = ["workspace", "productivity", "cli", "automation", "developer-tools" ]

[dependencies]
clap = "2.22"
slog-term = "1.5"
serde_json = "1.0.3"
serde = "1.0.3"
serde_derive = "1.0.3"
git2 = "0.6"
maplit = "0.1"
rayon = "0.8"
regex = "0.2"
ansi_term = "0.9"
atty = "0.2"
rand = "0.3"
spectral = "0.6"
crossbeam = "0.3"
indicatif = "0.7"
github-gql-rs = "0.0.1"

[dependencies.slog]
version = "1.5"
features = ["release_max_level_trace", "max_level_trace"]

[dev-dependencies]
spectral = "0.6"
